export interface Term {
  id: string;
  term: string;
  meaning: string;
  points: string;
}

export interface Category {
  id: string;
  title: string;
  terms: Term[];
}

export const studyData: Category[] = [
  {
    id: "ai",
    title: "① 生成AI・人工知能（AI）関連",
    terms: [
      { id: "ai-1", term: "生成モデル", meaning: "データの確率分布を学習し、新しいデータを生成するモデル", points: "GANや拡散モデルの土台" },
      { id: "ai-2", term: "敵対的生成ネットワーク（GAN）", meaning: "Generator（生成器）とDiscriminator（識別器）が競い合い学習する仕組み", points: "画像生成などに活用" },
      { id: "ai-3", term: "基盤モデル", meaning: "大量データで事前学習し、様々なタスクに転用できる大規模モデル", points: "GPT・BERTが代表例" },
      { id: "ai-4", term: "拡散モデル", meaning: "ノイズを徐々に除去することでデータを生成する生成AIの手法", points: "画像生成AIに多く採用" },
      { id: "ai-5", term: "言語モデル", meaning: "テキストの確率的パターンを学習し次の単語を予測するモデル", points: "LLMの基礎技術" },
      { id: "ai-6", term: "大規模言語モデル（LLM）", meaning: "膨大なテキストデータで学習した巨大な言語モデル", points: "ChatGPT・Claudeなど" },
      { id: "ai-7", term: "自己教師あり学習", meaning: "ラベルなしデータから教師信号を自動生成して学習する手法", points: "LLM事前学習に使用" },
      { id: "ai-8", term: "プロンプトエンジニアリング", meaning: "AIへの入力文（プロンプト）を工夫して望ましい出力を得る技術", points: "Few-shot / Zero-shot学習" },
      { id: "ai-9", term: "マルチモーダルAI", meaning: "テキスト・画像・音声など複数の種類のデータを扱えるAI", points: "GPT-4o等が該当" },
      { id: "ai-10", term: "ランダム性（Temperature）", meaning: "生成AIの出力のランダム度を制御するパラメータ", points: "高いほど多様・低いほど安定" },
      { id: "ai-11", term: "スケーリング則", meaning: "モデル規模・データ量・計算量を増やすと性能が向上する法則", points: "LLM開発の指針" },
      { id: "ai-12", term: "説明可能なAI（XAI）", meaning: "AIの判断根拠を人間が理解できる形で説明できるAI", points: "ブラックボックス問題への対応" },
      { id: "ai-13", term: "ヒューマンインザループ（HITL）", meaning: "AI処理の途中に人間が確認・判断を行う仕組み", points: "自動化の過信を防ぐ" },
      { id: "ai-14", term: "アルゴリズムのバイアス", meaning: "学習データの偏りにより、AIが不公平な判断をする問題", points: "差別・不平等の温床に" },
      { id: "ai-15", term: "AIサービスの責任論", meaning: "AIが起こした損害の責任を誰が負うかという議論", points: "開発者・利用者・運営者" },
      { id: "ai-16", term: "ハルシネーション", meaning: "AIが事実と異なる情報を自信を持って生成してしまう現象", points: "出力の検証が必須" },
      { id: "ai-17", term: "AIサービスのオプトアウトポリシー", meaning: "ユーザーがAIへのデータ提供・学習利用を拒否できる仕組み", points: "プライバシー保護に関連" },
      { id: "ai-18", term: "人間中心のAI社会原則", meaning: "AIを社会実装する際の基本原則（公平性・説明責任・透明性など）", points: "内閣府が策定" },
      { id: "ai-19", term: "AI利活用ガイドライン", meaning: "総務省などが示すAIを適切に活用するための指針", points: "利用者向けの留意事項" },
      { id: "ai-20", term: "AI開発ガイドライン", meaning: "経済産業省などが示すAI開発者向けの指針", points: "開発時の安全性・倫理" },
      { id: "ai-21", term: "AIの社会的受容性", meaning: "AIが社会に受け入れられるための信頼性・安全性に関する議論", points: "信頼の構築が鍵" },
      { id: "ai-22", term: "信頼できるAIのための倫理ガイドライン", meaning: "公平・透明・安全なAI実現のための倫理的指針", points: "国際的な議論のベース" },
      { id: "ai-23", term: "RAG（検索拡張生成）", meaning: "外部知識を検索し、その結果をプロンプトに含めて回答を生成する手法", points: "ハルシネーションの抑制に有効" },
      { id: "ai-24", term: "ファインチューニング", meaning: "学習済みモデルを特定のタスクやデータに合わせて微調整する手法", points: "専門領域への特化" },
      { id: "ai-25", term: "RLHF", meaning: "人間のフィードバックを元に強化学習を行い、AIの出力を人間に合わせる手法", points: "安全性・有用性の向上" },
      { id: "ai-26", term: "トークン", meaning: "AIがテキストを処理する際の最小単位（単語や文字の断片）", points: "課金や入力制限の単位" },
      { id: "ai-27", term: "転移学習", meaning: "ある領域で学習した知識を、別の関連する領域の学習に再利用する手法", points: "学習時間の短縮・高精度化" },
    ],
  },
  {
    id: "stats",
    title: "② 数理・統計（分析手法の高度化）",
    terms: [
      { id: "stats-1", term: "歪度", meaning: "データ分布の左右非対称性を表す指標（正規分布では0）", points: "正:右に裾が長い" },
      { id: "stats-2", term: "尖度", meaning: "データ分布の山の尖り具合を表す指標（正規分布では0または3）", points: "高いほど尖った分布" },
      { id: "stats-3", term: "相関と因果", meaning: "相関は関連性、因果は原因と結果の関係。相関≠因果", points: "擬似相関に注意" },
      { id: "stats-4", term: "擬似相関", meaning: "第三の変数（交絡変数）によって生じる見かけ上の相関", points: "「アイスと溺死者数」が例" },
      { id: "stats-5", term: "説明変数", meaning: "予測モデルで目的変数を説明・予測するために使う変数（X）", points: "特徴量・入力変数とも" },
      { id: "stats-6", term: "目的変数", meaning: "予測・説明したい対象の変数（Y）", points: "応答変数・出力変数とも" },
      { id: "stats-7", term: "尤度", meaning: "ある仮定のもとで観測データが得られる確からしさ", points: "対数尤度が最大化対象" },
      { id: "stats-8", term: "最尤推定", meaning: "観測データの尤度を最大にするパラメータを推定する方法", points: "機械学習でも広く使用" },
      { id: "stats-9", term: "仮説検定", meaning: "標本データからある仮説が正しいか統計的に判断する方法", points: "p値・有意水準を使う" },
      { id: "stats-10", term: "帰無仮説", meaning: "検定で「差がない・効果がない」と設定する仮説", points: "棄却を目指す仮説" },
      { id: "stats-11", term: "対立仮説", meaning: "帰無仮説が棄却されたときに採択される仮説", points: "「差がある」側の主張" },
      { id: "stats-12", term: "有意水準", meaning: "帰無仮説を誤って棄却する確率の許容値（通常5%または1%）", points: "a=0.05 が一般的" },
      { id: "stats-13", term: "p値（有意確率）", meaning: "帰無仮説が正しい場合に観測値以上の結果が出る確率", points: "p < a で仮説棄却" },
      { id: "stats-14", term: "棄却域", meaning: "帰無仮説を棄却する統計量の範囲", points: "両側・片側検定で異なる" },
      { id: "stats-15", term: "第1種の誤り", meaning: "帰無仮説が真なのに棄却してしまう誤り（偽陽性）", points: "= 有意水準 a" },
      { id: "stats-16", term: "第2種の誤り", meaning: "帰無仮説が偽なのに棄却しない誤り（偽陰性）", points: "= 1 - 検出力" },
      { id: "stats-17", term: "検出力（検定力）", meaning: "帰無仮説が偽のとき正しく棄却できる確率（1-b）", points: "高いほど良い検定" },
    ],
  },
  {
    id: "security",
    title: "③ セキュリティ（最新の脅威と対策技術）",
    terms: [
      { id: "sec-1", term: "二重脅迫（ダブルエクストーション）", meaning: "データを暗号化＋流出をちらつかせて身代金を要求する攻撃", points: "ランサムウェアの進化形" },
      { id: "sec-2", term: "サイバーキルチェーン", meaning: "攻撃者の行動を7段階で体系化したサイバー攻撃モデル", points: "偵察→武器化→…→実行" },
      { id: "sec-3", term: "スミッシング", meaning: "SMSを悪用したフィッシング詐欺攻撃", points: "URLクリックを誘導" },
      { id: "sec-4", term: "ディープフェイク", meaning: "AIが生成した本物そっくりの偽動画・音声・画像", points: "詐欺・誤情報に悪用" },
      { id: "sec-5", term: "敵対的サンプル（Adversarial Examples）", meaning: "人間には知覚できないノイズを加えAIを誤認識させる入力データ", points: "AIの脆弱性の一種" },
      { id: "sec-6", term: "プロンプトインジェクション", meaning: "悪意ある入力でAIに意図しない動作をさせる攻撃", points: "LLMへの新たな脅威" },
      { id: "sec-7", term: "3-2-1ルール", meaning: "データを3コピー・2種類のメディア・1つはオフサイト保管", points: "バックアップの鉄則" },
      { id: "sec-8", term: "WORM機能", meaning: "Write Once Read Many:一度書いたら変更・削除できないストレージ機能", points: "証拠改ざん防止に有効" },
      { id: "sec-9", term: "イミュータブルバックアップ", meaning: "変更・削除が不可能な状態でデータを保存するバックアップ", points: "ランサムウェア対策" },
      { id: "sec-10", term: "SBOM（ソフトウェア部品表）", meaning: "ソフトウェアを構成するコンポーネントの一覧（依存関係を含む）", points: "脆弱性管理の透明性" },
      { id: "sec-11", term: "AI for Security", meaning: "AIを使ってセキュリティ対策・脅威検知を行う技術", points: "異常検知・ログ分析" },
      { id: "sec-12", term: "Security for AI", meaning: "AI自体を攻撃から守るためのセキュリティ技術", points: "モデルの堅牢化" },
      { id: "sec-13", term: "ゼロトラスト", meaning: "「何も信頼しない」を前提に、全てのアクセスを検証するセキュリティ概念", points: "境界防御の限界に対応" },
      { id: "sec-14", term: "多要素認証（MFA）", meaning: "知識・所有・生体などの異なる要素を2つ以上組み合わせて認証する手法", points: "不正アクセスの防止" },
      { id: "sec-15", term: "シャドーIT", meaning: "会社の許可を得ずに業務で利用されているIT機器やサービス", points: "情報漏洩のリスク" },
      { id: "sec-16", term: "EDR", meaning: "PCやサーバーなどのエンドポイントにおける挙動を監視・対応する技術", points: "侵入後の検知・対応" },
    ],
  },
  {
    id: "infra",
    title: "④ 開発技術・インフラ",
    terms: [
      { id: "infra-1", term: "IaC（Infrastructure as Code）", meaning: "インフラ構成をコードで定義・管理する手法", points: "Terraform・Ansible等" },
      { id: "infra-2", term: "AIOps", meaning: "AIを活用してITシステムの運用・監視・障害対応を自動化する技術", points: "運用効率の向上" },
      { id: "infra-3", term: "クリーンアーキテクチャ", meaning: "依存関係を整理し保守性・テスト容易性を高めるソフトウェア設計手法", points: "関心の分離" },
      { id: "infra-4", term: "スプリントバックログ", meaning: "スクラム開発において1スプリント内に実施する作業の一覧", points: "開発チームが管理" },
      { id: "infra-5", term: "クラウドバイデフォルト", meaning: "システム構築の際にクラウド利用を第一候補とする方針", points: "政府情報システムの方針" },
      { id: "infra-6", term: "ソブリンクラウド", meaning: "データの主権・管轄権を守ることを重視したクラウドの形態", points: "法的規制への対応" },
      { id: "infra-7", term: "Webクローリング", meaning: "Webサイトを自動巡回してデータを収集する技術", points: "検索エンジンの基盤" },
      { id: "infra-8", term: "スクレイピング", meaning: "Webページから必要なデータを自動抽出する技術", points: "利用規約に注意" },
      { id: "infra-9", term: "データレイク", meaning: "構造化・非構造化を問わず大量データをそのまま蓄積するストレージ", points: "ビッグデータ分析の基盤" },
      { id: "infra-10", term: "データのサイロ化", meaning: "部門・システム間でデータが孤立し、連携・活用できない状態", points: "DX推進の障壁" },
      { id: "infra-11", term: "サーバーレス", meaning: "サーバーの管理を意識せず、コードの実行単位で利用できるクラウド形態", points: "FaaS・BaaS等" },
      { id: "infra-12", term: "マイクロサービス", meaning: "巨大なアプリを小さな独立したサービスの集合体として開発する手法", points: "疎結合・独立したデプロイ" },
      { id: "infra-13", term: "コンテナ", meaning: "アプリとその実行環境をパッケージ化し、軽量に動作させる技術", points: "Docker・Kubernetes" },
    ],
  },
  {
    id: "legal",
    title: "⑤ 社会・倫理・法務",
    terms: [
      { id: "legal-1", term: "マルインフォメーション", meaning: "事実に基づいているが、誰かを傷つける意図で使われる情報", points: "悪意ある事実の拡散" },
      { id: "legal-2", term: "ディスインフォメーション", meaning: "意図的に人を誤導するために作成・拡散される偽情報", points: "フェイクニュース等" },
      { id: "legal-3", term: "ミスインフォメーション", meaning: "悪意はないが誤っている情報（誤解・勘違いで拡散）", points: "3種の誤情報の一つ" },
      { id: "legal-4", term: "ヘイトスピーチ", meaning: "特定の人種・宗教・性別などへの憎悪・差別を扇動する表現", points: "人権侵害の問題" },
      { id: "legal-5", term: "エコーチェンバー", meaning: "同じ意見の人だけが集まり意見が増幅・強化される現象", points: "SNSでの偏り" },
      { id: "legal-6", term: "フィルターバブル", meaning: "アルゴリズムが自分の好みに合う情報のみを提示し視野が狭まる現象", points: "情報の孤立化" },
      { id: "legal-7", term: "ファクトチェック", meaning: "報道・情報の事実確認・検証を行う活動", points: "真偽の検証" },
      { id: "legal-8", term: "ELSI", meaning: "Ethical, Legal, and Social Issues:技術の倫理的・法的・社会的課題", points: "新技術導入時の検討" },
      { id: "legal-9", term: "デジタルタトゥー", meaning: "一度インターネットに公開した情報は完全に消去できないという問題", points: "プライバシー・名誉毀損" },
      { id: "legal-10", term: "ペアレンタルコントロール", meaning: "保護者が子供のインターネット利用を制限・管理する仕組み", points: "フィルタリング等" },
      { id: "legal-11", term: "ベースレジストリ", meaning: "国が管理する住所・法人など社会の基本情報を集約した公的基礎情報DB", points: "行政DXの基盤" },
      { id: "legal-12", term: "デジタル庁", meaning: "デジタル社会形成のための日本の行政機関（2021年設置）", points: "司令塔機能" },
      { id: "legal-13", term: "ビジネスと人権", meaning: "企業は人権を尊重する責任を持つという国際的な原則・枠組み", points: "デューデリジェンス" },
      { id: "legal-14", term: "適格請求書等保存方式", meaning: "消費税の仕入税額控除に必要な適格請求書（インボイス）を保存する制度", points: "インボイス制度" },
      { id: "legal-15", term: "官民データ活用推進基本法", meaning: "官民のデータ活用を促進し、デジタル社会形成を推進する法律", points: "オープンデータの推進" },
      { id: "legal-16", term: "GX", meaning: "化石燃料依存から脱却し、クリーンエネルギー中心の社会・経済へ変革する取り組み", points: "グリーントランスフォーメーション" },
      { id: "legal-17", term: "GXリーグ基本構想", meaning: "GX実現に向けて産官学が連携して取り組む枠組み", points: "排出量取引等" },
      { id: "legal-18", term: "カーボントレーシング", meaning: "製品・サービスのライフサイクル全体における温室効果ガス排出量を追跡・可視化する仕組み", points: "排出量の見える化" },
      { id: "legal-19", term: "GX推進法", meaning: "GXを推進するための投資・規制・支援措置を定めた法律", points: "脱炭素成長型経済構造" },
      { id: "legal-20", term: "GX脱炭素電源法", meaning: "再生可能エネルギーや原子力などの脱炭麻電源の活用を推進する法律", points: "エネルギー安定供給" },
      { id: "legal-21", term: "ダークパターン", meaning: "ユーザーを欺き、意図しない行動（購入や契約）を促す不適切なUI設計", points: "倫理的・法的な問題" },
      { id: "legal-22", term: "デジタル・ディバイド", meaning: "情報通信技術（IT）を利用できる人とできない人の間に生じる格差", points: "機会の不平等" },
    ],
  },

];
